[package]
name = "chess_engine"
version = "0.1.0"
edition = "2021"

[dependencies]
# Optional: uncomment for better terminal control
# crossterm = "0.27"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
